// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';
import { Observable } from 'rxjs';
import { map, filter } from 'rxjs/operators';

import { SwitchSwitchPairPairingPort } from '../models/switch-switch-pair-pairing-port';
import { SwitchSwitchPairPairingPortList } from '../models/switch-switch-pair-pairing-port-list';

@Injectable({
  providedIn: 'root',
})
export class SwitchSwitchPairPairingPortService extends BaseService {
  constructor(
    config: ApiConfiguration,
    http: HttpClient
  ) {
    super(config, http);
  }

  /**
   * Path part for operation getSwitchSwitchPairPairingPortList
   */
  static readonly GetSwitchSwitchPairPairingPortListPath = '/sdn-fabric/v0.1.x/{fabric-id}/switch/{switch-id}/switch-pair/pairing-port';

  /**
   * GET /switch/{switch-id}/switch-pair/pairing-port List.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSwitchSwitchPairPairingPortList()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSwitchSwitchPairPairingPortList$Response(params: {

    /**
     * fabric-id (target in onos-config)
     */
    'fabric-id': any;

    /**
     * key {switch-id}
     */
    'switch-id': any;
  }): Observable<StrictHttpResponse<SwitchSwitchPairPairingPortList>> {

    const rb = new RequestBuilder(this.rootUrl, SwitchSwitchPairPairingPortService.GetSwitchSwitchPairPairingPortListPath, 'get');
    if (params) {
      rb.path('fabric-id', params['fabric-id'], {});
      rb.path('switch-id', params['switch-id'], {});
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'application/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<SwitchSwitchPairPairingPortList>;
      })
    );
  }

  /**
   * GET /switch/{switch-id}/switch-pair/pairing-port List.
   *
   *
   *
   * This method provides access to only to the response body.
   * To access the full response (for headers, for example), `getSwitchSwitchPairPairingPortList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSwitchSwitchPairPairingPortList(params: {

    /**
     * fabric-id (target in onos-config)
     */
    'fabric-id': any;

    /**
     * key {switch-id}
     */
    'switch-id': any;
  }): Observable<SwitchSwitchPairPairingPortList> {

    return this.getSwitchSwitchPairPairingPortList$Response(params).pipe(
      map((r: StrictHttpResponse<SwitchSwitchPairPairingPortList>) => r.body as SwitchSwitchPairPairingPortList)
    );
  }

  /**
   * Path part for operation getSwitchSwitchPairPairingPort
   */
  static readonly GetSwitchSwitchPairPairingPortPath = '/sdn-fabric/v0.1.x/{fabric-id}/switch/{switch-id}/switch-pair/pairing-port/{cage-number}/{channel-number}';

  /**
   * GET /switch/{switch-id}/switch-pair/pairing-port Container.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSwitchSwitchPairPairingPort()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSwitchSwitchPairPairingPort$Response(params: {

    /**
     * fabric-id (target in onos-config)
     */
    'fabric-id': any;

    /**
     * key {switch-id}
     */
    'switch-id': any;

    /**
     * key {cage-number}
     */
    'cage-number': any;

    /**
     * key {channel-number}
     */
    'channel-number': any;
  }): Observable<StrictHttpResponse<SwitchSwitchPairPairingPort>> {

    const rb = new RequestBuilder(this.rootUrl, SwitchSwitchPairPairingPortService.GetSwitchSwitchPairPairingPortPath, 'get');
    if (params) {
      rb.path('fabric-id', params['fabric-id'], {});
      rb.path('switch-id', params['switch-id'], {});
      rb.path('cage-number', params['cage-number'], {});
      rb.path('channel-number', params['channel-number'], {});
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'application/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<SwitchSwitchPairPairingPort>;
      })
    );
  }

  /**
   * GET /switch/{switch-id}/switch-pair/pairing-port Container.
   *
   *
   *
   * This method provides access to only to the response body.
   * To access the full response (for headers, for example), `getSwitchSwitchPairPairingPort$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSwitchSwitchPairPairingPort(params: {

    /**
     * fabric-id (target in onos-config)
     */
    'fabric-id': any;

    /**
     * key {switch-id}
     */
    'switch-id': any;

    /**
     * key {cage-number}
     */
    'cage-number': any;

    /**
     * key {channel-number}
     */
    'channel-number': any;
  }): Observable<SwitchSwitchPairPairingPort> {

    return this.getSwitchSwitchPairPairingPort$Response(params).pipe(
      map((r: StrictHttpResponse<SwitchSwitchPairPairingPort>) => r.body as SwitchSwitchPairPairingPort)
    );
  }

}
