sudo: false

language: node_js
node_js:
    - "12"

services:
    - docker

notifications:
    email: false

branches:
    only:
        - master

addons:
    apt:
        packages:
            - chromium-browser

cache:
    directories:
        - ./node_modules
        - ./dist

before_script:
    - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd

install:
    - npm install -g @angular/cli
    - npm install

jobs:
    include:
        - stage: tests
          if: type == pull_request || fork == false
          script:
              - make test
        - stage: docs build
          if: type != pull_request && fork == false
          script:
              - sh build/bin/trigger-docs-travis $TRAVIS_ACCESS_TOKEN
        - stage: release
          if: type != pull_request && fork == false
          script:
              - bash ./build/bin/push-images
              - bash ../build-tools/release-merge-commit
