// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

/**
 * To optionally omit 'required' properties, add them to 'unchanged' list
 */
export interface AdditionalPropertyUnchanged {

  /**
   * A comma seperated list of unchanged mandatory attribute names
   */
  unchanged?: string;
}
