// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

/**
 * Optionally specify a target other than the default (only on PATCH method)
 */
export interface AdditionalPropertyTarget {

  /**
   * an override of the target (target)
   */
  target?: string;
}
