// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { ConnectivityServicesConnectivityService } from './connectivity-services-connectivity-service';

/**
 * List of connectivity services (list)
 */
export type ConnectivityServicesConnectivityServiceList = Array<ConnectivityServicesConnectivityService>;
