// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteDevice } from './enterprises-enterprise-site-device';

/**
 * List of devices (list)
 */
export type EnterprisesEnterpriseSiteDeviceList = Array<EnterprisesEnterpriseSiteDevice>;
