// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

/**
 * List of devices (single)
 */
export interface EnterprisesEnterpriseSiteDevice {

  /**
   * long description field
   */
  description?: string;

  /**
   * ID for this device.
   */
  'device-id': string;

  /**
   * display name to use in GUI or CLI
   */
  'display-name'?: string;

  /**
   * IMEI for this device
   */
  imei?: string;

  /**
   * Link to simcard
   */
  'sim-card'?: string;
}
