// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteUpf } from './enterprises-enterprise-site-upf';

/**
 * A list of named upfs. (list)
 */
export type EnterprisesEnterpriseSiteUpfList = Array<EnterprisesEnterpriseSiteUpf>;
