// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseTemplate } from './enterprises-enterprise-template';

/**
 * List of slice templates (list)
 */
export type EnterprisesEnterpriseTemplateList = Array<EnterprisesEnterpriseTemplate>;
