// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseTrafficClass } from './enterprises-enterprise-traffic-class';

/**
 * List of traffic class (list)
 */
export type EnterprisesEnterpriseTrafficClassList = Array<EnterprisesEnterpriseTrafficClass>;
