// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteSlice } from './enterprises-enterprise-site-slice';

/**
 * List of Slices (list)
 */
export type EnterprisesEnterpriseSiteSliceList = Array<EnterprisesEnterpriseSiteSlice>;
