// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteDeviceGroup } from './enterprises-enterprise-site-device-group';

/**
 * List of device groups (list)
 */
export type EnterprisesEnterpriseSiteDeviceGroupList = Array<EnterprisesEnterpriseSiteDeviceGroup>;
