// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

/**
 * For choice bitrate:gbr-case
 */
export interface EnterprisesEnterpriseSiteSlicePriorityTrafficRuleGbr {

  /**
   * Per-Device per application downlink data rate in bps
   */
  downlink?: number;

  /**
   * Per-Device per-Application uplink data rate in bps
   */
  uplink?: number;
}
