// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterprise } from './enterprises-enterprise';

/**
 * List of enterprises (list)
 */
export type EnterprisesEnterpriseList = Array<EnterprisesEnterprise>;
