// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteIpDomain } from './enterprises-enterprise-site-ip-domain';

/**
 * List of ip domains (list)
 */
export type EnterprisesEnterpriseSiteIpDomainList = Array<EnterprisesEnterpriseSiteIpDomain>;
