// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

/**
 * The list for connectivity-service (single)
 */
export interface EnterprisesEnterpriseConnectivityService {

  /**
   * Link to connectivity services where configuration should be pushed for this enterprise's devices
   */
  'connectivity-service': string;

  /**
   * Allow or disallow pushes to this connectivity service
   */
  enabled?: boolean;
}
