// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteSliceDeviceGroup } from './enterprises-enterprise-site-slice-device-group';

/**
 * A list of device groups. Groups will only participate in
 * the Slice if the enable field is set to True (list)
 */
export type EnterprisesEnterpriseSiteSliceDeviceGroupList = Array<EnterprisesEnterpriseSiteSliceDeviceGroup>;
