// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseApplicationEndpoint } from './enterprises-enterprise-application-endpoint';

/**
 * list for endpoint (list)
 */
export type EnterprisesEnterpriseApplicationEndpointList = Array<EnterprisesEnterpriseApplicationEndpoint>;
