// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteDeviceGroupDevice } from './enterprises-enterprise-site-device-group-device';

/**
 * list of devices in this device-group (list)
 */
export type EnterprisesEnterpriseSiteDeviceGroupDeviceList = Array<EnterprisesEnterpriseSiteDeviceGroupDevice>;
