// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

/**
 * list of devices in this device-group (single)
 */
export interface EnterprisesEnterpriseSiteDeviceGroupDevice {

  /**
   * Link to device
   */
  'device-id': string;

  /**
   * Enable this device
   */
  enable?: boolean;
}
