// Code generated by openapi-gen. DO NOT EDIT.
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */
import { EnterprisesEnterpriseSiteSliceFilter } from './enterprises-enterprise-site-slice-filter';

/**
 * A list of applications to allow and/or deny. Rules are executed in
 * priority order. The first rule to match will determine the fate
 * of the packet. (list)
 */
export type EnterprisesEnterpriseSiteSliceFilterList = Array<EnterprisesEnterpriseSiteSliceFilter>;
