// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * Optionally specify a enterprise-id other than the default (only on PATCH method)
 */
export interface AdditionalPropertyEnterpriseId {

  /**
   * an override of the enterprise-id (target)
   */
  'enterprise-id'?: string;
}
