// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * Maximum bitrate
 */
export interface ApplicationEndpointMbr {

  /**
   * Per-Device per application MBR downlink data rate in bps
   */
  downlink?: number;

  /**
   * Per-Device per-Application MBR uplink data rate in bps
   */
  uplink?: number;
}
