// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { ApplicationEndpoint } from './application-endpoint';

/**
 * list for endpoint (list)
 */
export type ApplicationEndpointList = Array<ApplicationEndpoint>;
