// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { LeafRefOption } from './leaf-ref-option';

/**
 * List of label/value of leafref options
 */
export type LeafRefOptions = Array<LeafRefOption>;
