// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteSimCard } from './site-sim-card';

/**
 * List of sim cards (list)
 */
export type SiteSimCardList = Array<SiteSimCard>;
