// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyUnchanged } from './additional-property-unchanged';
import { SiteDeviceGroupDeviceList } from './site-device-group-device-list';
import { SiteDeviceGroupMbr } from './site-device-group-mbr';

/**
 * List of device groups (single)
 */
export interface SiteDeviceGroup {

  /**
   * long description field
   */
  description?: string;
  device?: SiteDeviceGroupDeviceList;

  /**
   * ID for this device group.
   */
  'device-group-id': string;

  /**
   * display name to use in GUI or CLI
   */
  'display-name'?: string;

  /**
   * Link to ip-domain settings that determine the pool of IP addresses,
   * as well as the domain resolver settings to use
   */
  'ip-domain'?: string;
  mbr?: SiteDeviceGroupMbr;

  /**
   * Link to traffic class
   */
  'traffic-class': string;

  [key: string]: AdditionalPropertyUnchanged | SiteDeviceGroupDeviceList | SiteDeviceGroupMbr | string | undefined;
}
