// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteSlice } from './site-slice';

/**
 * List of Slices (list)
 */
export type SiteSliceList = Array<SiteSlice>;
