// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteIpDomain } from './site-ip-domain';

/**
 * List of ip domains (list)
 */
export type SiteIpDomainList = Array<SiteIpDomain>;
