// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteDevice } from './site-device';

/**
 * List of devices (list)
 */
export type SiteDeviceList = Array<SiteDevice>;
