// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteSliceDeviceGroup } from './site-slice-device-group';

/**
 * A list of device groups. Groups will only participate in
 * the Slice if the enable field is set to True (list)
 */
export type SiteSliceDeviceGroupList = Array<SiteSliceDeviceGroup>;
