// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * For choice bitrate:mbr-case
 */
export interface SiteSlicePriorityTrafficRuleMbr {

  /**
   * Per-Device per application downlink data rate in bps
   */
  downlink?: number;

  /**
   * Per-Device per-Application uplink data rate in bps
   */
  uplink?: number;
}
