// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteSliceFilter } from './site-slice-filter';

/**
 * A list of applications to allow and/or deny. Rules are executed in
 * priority order. The first rule to match will determine the fate
 * of the packet. (list)
 */
export type SiteSliceFilterList = Array<SiteSliceFilter>;
