// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * The 4g core endpoint
 */
export interface SiteConnectivityServiceCore4G {

  /**
   * URL of ACC prometheus
   */
  'acc-prometheus-url'?: string;

  /**
   * Endpoint URL
   */
  endpoint?: string;
}
