// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteMonitoringEdgeDevice } from './site-monitoring-edge-device';

/**
 * List of edge monitoring devices (list)
 */
export type SiteMonitoringEdgeDeviceList = Array<SiteMonitoringEdgeDevice>;
