// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyUnchanged } from './additional-property-unchanged';

/**
 * Maximum bitrate
 */
export interface SiteDeviceGroupMbr {

  /**
   * Per-device MBR downlink data rate in bps
   */
  downlink: number;

  /**
   * Per-device MBR uplink data rate in bps
   */
  uplink: number;

  [key: string]: AdditionalPropertyUnchanged | number;
}
