// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SiteSmallCell } from './site-small-cell';

/**
 * List of small cell addresses (list)
 */
export type SiteSmallCellList = Array<SiteSmallCell>;
