// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * Connectivity to the xApp
 */
export interface SiteConnectivityServiceRan5GService {

  /**
   * xApp Endpoint URL
   */
  'xapp-endpoint'?: string;
}
