// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyUnchanged } from './additional-property-unchanged';
import { TemplateMbr } from './template-mbr';

/**
 * List of slice templates (single)
 */
export interface Template {

  /**
   * Default behavior if no filter rules match
   */
  'default-behavior': string;

  /**
   * long description field
   */
  description?: string;

  /**
   * display name to use in GUI or CLI
   */
  'display-name'?: string;
  mbr?: TemplateMbr;

  /**
   * Slice differentiator
   */
  sd?: string;

  /**
   * Slice/Service type
   */
  sst?: string;

  /**
   * ID for this slice template.
   */
  'template-id': string;

  [key: string]: AdditionalPropertyUnchanged | TemplateMbr | string | undefined;
}
