// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { Template } from './template';

/**
 * List of slice templates (list)
 */
export type TemplateList = Array<Template>;
