// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * Per-Slice QOS Settings Maximum Bit Rate
 */
export interface TemplateMbr {

  /**
   * Per-Slice MBR downlink data rate in bps
   */
  downlink?: number;

  /**
   * Per-Slice Downlink burst size
   */
  'downlink-burst-size'?: number;

  /**
   * Per-Slice MBR uplink data rate in bps
   */
  uplink?: number;

  /**
   * Per-Slice Uplink burst size
   */
  'uplink-burst-size'?: number;
}
