// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyEnterpriseId } from './additional-property-enterprise-id';

/**
 * List of traffic class (single)
 */
export interface TrafficClass {

  /**
   * Allocation and Retention Priority. 1 is the highest. 15 is the lowest.
   */
  arp?: number;

  /**
   * long description field
   */
  description?: string;

  /**
   * display name to use in GUI or CLI
   */
  'display-name'?: string;

  /**
   * PDB
   */
  pdb?: number;

  /**
   * PELR exponent
   */
  pelr?: number;

  /**
   * QOS Class Identifier
   */
  qci?: number;

  /**
   * ID for this traffic class.
   */
  'traffic-class-id': string;

  [key: string]: AdditionalPropertyEnterpriseId | number | string | undefined;
}
