// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';
import { Observable } from 'rxjs';
import { map, filter } from 'rxjs/operators';

import { LeafRefOptions } from '../models/leaf-ref-options';

@Injectable({
  providedIn: 'root',
})
export class ApplicationEndpointTrafficClassService extends BaseService {
  constructor(
    config: ApiConfiguration,
    http: HttpClient
  ) {
    super(config, http);
  }

  /**
   * Path part for operation getApplicationEndpointTrafficClassValuesLeafref
   */
  static readonly GetApplicationEndpointTrafficClassValuesLeafrefPath = '/aether/v2.1.x/{enterprise-id}/application/{application-id}/endpoint/{endpoint-id}/traffic-class/values';

  /**
   * GET /application/{application-id}/endpoint/{endpoint-id}/traffic-class/values Leafref.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getApplicationEndpointTrafficClassValuesLeafref()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApplicationEndpointTrafficClassValuesLeafref$Response(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {application-id}
     */
    'application-id': any;

    /**
     * key {endpoint-id}
     */
    'endpoint-id': any;
  }): Observable<StrictHttpResponse<LeafRefOptions>> {

    const rb = new RequestBuilder(this.rootUrl, ApplicationEndpointTrafficClassService.GetApplicationEndpointTrafficClassValuesLeafrefPath, 'get');
    if (params) {
      rb.path('enterprise-id', params['enterprise-id'], {});
      rb.path('application-id', params['application-id'], {});
      rb.path('endpoint-id', params['endpoint-id'], {});
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'application/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<LeafRefOptions>;
      })
    );
  }

  /**
   * GET /application/{application-id}/endpoint/{endpoint-id}/traffic-class/values Leafref.
   *
   *
   *
   * This method provides access to only to the response body.
   * To access the full response (for headers, for example), `getApplicationEndpointTrafficClassValuesLeafref$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApplicationEndpointTrafficClassValuesLeafref(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {application-id}
     */
    'application-id': any;

    /**
     * key {endpoint-id}
     */
    'endpoint-id': any;
  }): Observable<LeafRefOptions> {

    return this.getApplicationEndpointTrafficClassValuesLeafref$Response(params).pipe(
      map((r: StrictHttpResponse<LeafRefOptions>) => r.body as LeafRefOptions)
    );
  }

}
