// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';
import { Observable } from 'rxjs';
import { map, filter } from 'rxjs/operators';

import { SiteConnectivityServiceCore4G } from '../models/site-connectivity-service-core-4-g';
import { SiteConnectivityServiceCore5G } from '../models/site-connectivity-service-core-5-g';

@Injectable({
  providedIn: 'root',
})
export class SiteConnectivityServiceService extends BaseService {
  constructor(
    config: ApiConfiguration,
    http: HttpClient
  ) {
    super(config, http);
  }

  /**
   * Path part for operation getSiteConnectivityServiceCore4G
   */
  static readonly GetSiteConnectivityServiceCore4GPath = '/aether/v2.1.x/{enterprise-id}/site/{site-id}/connectivity-service/core-4g';

  /**
   * GET /site/{site-id}/connectivity-service/core-4g Container.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSiteConnectivityServiceCore4G()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteConnectivityServiceCore4G$Response(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;
  }): Observable<StrictHttpResponse<SiteConnectivityServiceCore4G>> {

    const rb = new RequestBuilder(this.rootUrl, SiteConnectivityServiceService.GetSiteConnectivityServiceCore4GPath, 'get');
    if (params) {
      rb.path('enterprise-id', params['enterprise-id'], {});
      rb.path('site-id', params['site-id'], {});
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'application/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<SiteConnectivityServiceCore4G>;
      })
    );
  }

  /**
   * GET /site/{site-id}/connectivity-service/core-4g Container.
   *
   *
   *
   * This method provides access to only to the response body.
   * To access the full response (for headers, for example), `getSiteConnectivityServiceCore4G$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteConnectivityServiceCore4G(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;
  }): Observable<SiteConnectivityServiceCore4G> {

    return this.getSiteConnectivityServiceCore4G$Response(params).pipe(
      map((r: StrictHttpResponse<SiteConnectivityServiceCore4G>) => r.body as SiteConnectivityServiceCore4G)
    );
  }

  /**
   * Path part for operation getSiteConnectivityServiceCore5G
   */
  static readonly GetSiteConnectivityServiceCore5GPath = '/aether/v2.1.x/{enterprise-id}/site/{site-id}/connectivity-service/core-5g';

  /**
   * GET /site/{site-id}/connectivity-service/core-5g Container.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSiteConnectivityServiceCore5G()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteConnectivityServiceCore5G$Response(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;
  }): Observable<StrictHttpResponse<SiteConnectivityServiceCore5G>> {

    const rb = new RequestBuilder(this.rootUrl, SiteConnectivityServiceService.GetSiteConnectivityServiceCore5GPath, 'get');
    if (params) {
      rb.path('enterprise-id', params['enterprise-id'], {});
      rb.path('site-id', params['site-id'], {});
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'application/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<SiteConnectivityServiceCore5G>;
      })
    );
  }

  /**
   * GET /site/{site-id}/connectivity-service/core-5g Container.
   *
   *
   *
   * This method provides access to only to the response body.
   * To access the full response (for headers, for example), `getSiteConnectivityServiceCore5G$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteConnectivityServiceCore5G(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;
  }): Observable<SiteConnectivityServiceCore5G> {

    return this.getSiteConnectivityServiceCore5G$Response(params).pipe(
      map((r: StrictHttpResponse<SiteConnectivityServiceCore5G>) => r.body as SiteConnectivityServiceCore5G)
    );
  }

}
