// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';
import { Observable } from 'rxjs';
import { map, filter } from 'rxjs/operators';

import { SiteUpf } from '../models/site-upf';
import { SiteUpfList } from '../models/site-upf-list';

@Injectable({
  providedIn: 'root',
})
export class SiteUpfService extends BaseService {
  constructor(
    config: ApiConfiguration,
    http: HttpClient
  ) {
    super(config, http);
  }

  /**
   * Path part for operation getSiteUpfList
   */
  static readonly GetSiteUpfListPath = '/aether/v2.1.x/{enterprise-id}/site/{site-id}/upf';

  /**
   * GET /site/{site-id}/upf List.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSiteUpfList()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteUpfList$Response(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;
  }): Observable<StrictHttpResponse<SiteUpfList>> {

    const rb = new RequestBuilder(this.rootUrl, SiteUpfService.GetSiteUpfListPath, 'get');
    if (params) {
      rb.path('enterprise-id', params['enterprise-id'], {});
      rb.path('site-id', params['site-id'], {});
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'application/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<SiteUpfList>;
      })
    );
  }

  /**
   * GET /site/{site-id}/upf List.
   *
   *
   *
   * This method provides access to only to the response body.
   * To access the full response (for headers, for example), `getSiteUpfList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteUpfList(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;
  }): Observable<SiteUpfList> {

    return this.getSiteUpfList$Response(params).pipe(
      map((r: StrictHttpResponse<SiteUpfList>) => r.body as SiteUpfList)
    );
  }

  /**
   * Path part for operation getSiteUpf
   */
  static readonly GetSiteUpfPath = '/aether/v2.1.x/{enterprise-id}/site/{site-id}/upf/{upf-id}';

  /**
   * GET /site/{site-id}/upf Container.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSiteUpf()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteUpf$Response(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;

    /**
     * key {upf-id}
     */
    'upf-id': any;
  }): Observable<StrictHttpResponse<SiteUpf>> {

    const rb = new RequestBuilder(this.rootUrl, SiteUpfService.GetSiteUpfPath, 'get');
    if (params) {
      rb.path('enterprise-id', params['enterprise-id'], {});
      rb.path('site-id', params['site-id'], {});
      rb.path('upf-id', params['upf-id'], {});
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'application/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<SiteUpf>;
      })
    );
  }

  /**
   * GET /site/{site-id}/upf Container.
   *
   *
   *
   * This method provides access to only to the response body.
   * To access the full response (for headers, for example), `getSiteUpf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSiteUpf(params: {

    /**
     * enterprise-id (target in onos-config)
     */
    'enterprise-id': any;

    /**
     * key {site-id}
     */
    'site-id': any;

    /**
     * key {upf-id}
     */
    'upf-id': any;
  }): Observable<SiteUpf> {

    return this.getSiteUpf$Response(params).pipe(
      map((r: StrictHttpResponse<SiteUpf>) => r.body as SiteUpf)
    );
  }

}
