// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * both the additional property 'unchanged' and the 'fabric-id'
 */
export interface AdditionalPropertiesUnchTarget {

  /**
   * an override of the fabric-id (target)
   */
  'fabric-id'?: string;

  /**
   * A comma seperated list of unchanged mandatory attribute names
   */
  unchanged?: string;
}
