// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * Optionally specify a fabric-id other than the default (only on PATCH method)
 */
export interface AdditionalPropertyFabricId {

  /**
   * an override of the fabric-id (target)
   */
  'fabric-id'?: string;
}
