// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { DhcpServer } from './dhcp-server';

/**
 * A list of DHCP Servers (list)
 */
export type DhcpServerList = Array<DhcpServer>;
