// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SwitchSwitchPairPairingPortList } from './switch-switch-pair-pairing-port-list';

/**
 * A Switch pairing. A switch can participate on 0-1 pairings
 */
export interface SwitchSwitchPair {

  /**
   * Paired switch identifier. A guard rail will require that
   * this field is present when the pairing-port list has at least 1 elements
   */
  'paired-switch'?: string;
  'pairing-port'?: SwitchSwitchPairPairingPortList;
}
