// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyUnchanged } from './additional-property-unchanged';

/**
 * a map of extra attributes: string-string (single)
 */
export interface SwitchModelAttribute {

  /**
   * the key in a map of attributes
   */
  'attribute-key': string;

  /**
   * the value of attribute-key
   */
  value: string;

  [key: string]: AdditionalPropertyUnchanged | string;
}
