// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyUnchanged } from './additional-property-unchanged';
import { SwitchPortDhcpConnectPoint } from './switch-port-dhcp-connect-point';
import { SwitchPortState } from './switch-port-state';
import { SwitchPortVlans } from './switch-port-vlans';

/**
 * A port in a switch (single)
 */
export interface SwitchPort {

  /**
   * reference to the cage-number of the port in the switch model
   */
  'cage-number': number;

  /**
   * reference to the channel-number of the port in the switch model
   */
  'channel-number': number;

  /**
   * long description field
   */
  description?: string;
  'dhcp-connect-point'?: SwitchPortDhcpConnectPoint;

  /**
   * display name to use in GUI or CLI
   */
  'display-name'?: string;

  /**
   * configured port speed
   */
  speed: 'speed-100g' | 'speed-10g' | 'speed-1g' | 'speed-2-5g' | 'speed-25g' | 'speed-400g' | 'speed-40g' | 'speed-5g' | 'speed-autoneg';
  state?: SwitchPortState;
  vlans?: SwitchPortVlans;

  [key: string]: 'speed-100g' | 'speed-10g' | 'speed-1g' | 'speed-2-5g' | 'speed-25g' | 'speed-400g' | 'speed-40g' | 'speed-5g' | 'speed-autoneg' | AdditionalPropertyUnchanged | SwitchPortDhcpConnectPoint | SwitchPortState | SwitchPortVlans | number | string | undefined;
}
