// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyUnchanged } from './additional-property-unchanged';
import { SwitchModelPortSpeeds } from './switch-model-port-speeds';

/**
 * A port in a switch (single)
 */
export interface SwitchModelPort {

  /**
   * identifier of the cage - physical port on switch
   */
  'cage-number': number;

  /**
   * channel in the port. 0 by default. A splitter can divide the port in to channels
   */
  'channel-number': number;

  /**
   * long description field
   */
  description?: string;

  /**
   * display name to use in GUI or CLI
   */
  'display-name'?: string;
  speeds?: SwitchModelPortSpeeds;

  [key: string]: AdditionalPropertyUnchanged | SwitchModelPortSpeeds | number | string | undefined;
}
