// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * Op state attributes
 */
export interface SwitchState {

  /**
   * status of the port: up|down
   */
  connected?: string;

  /**
   * Last known time the switch was connected
   */
  'last-connected'?: string;
}
