// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SwitchSwitchPairPairingPort } from './switch-switch-pair-pairing-port';

/**
 * The port on the local switch to establish the paired link
 * In future there may be more than 1 port to provide redundancy.
 * For the initial version this is limited to 1 (list)
 */
export type SwitchSwitchPairPairingPortList = Array<SwitchSwitchPairPairingPort>;
