// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AdditionalPropertyUnchanged } from './additional-property-unchanged';

/**
 * Op state attributes
 */
export interface SwitchPortState {

  /**
   * The desired state of the interface.  In RFC 7223 this leaf
   * has the same read semantics as ifAdminStatus.  Here, it
   * reflects the administrative state as set by enabling or
   * disabling the interface.
   */
  'admin-status'?: string;

  /**
   * System assigned number for each interface.  Corresponds to
   * ifIndex object in SNMP Interface MIB
   */
  ifindex?: number;

  /**
   * This timestamp indicates the time of the last state change
   * of the interface (e.g., up-to-down transition). This
   * corresponds to the ifLastChange object in the standard
   * interface MIB.
   *
   * The value is the timestamp in nanoseconds relative to
   * the Unix Epoch (Jan 1, 1970 00:00:00 UTC).
   */
  'last-change'?: number;

  /**
   * The current operational state of the interface.
   *
   * This leaf has the same semantics as ifOperStatus.
   */
  'oper-status'?: string;

  [key: string]: AdditionalPropertyUnchanged | number | string | undefined;
}
