// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SwitchVlanSubnet } from './switch-vlan-subnet';

/**
 * a list of VLANs (single)
 */
export interface SwitchVlan {

  /**
   * long description field
   */
  description?: string;

  /**
   * display name to use in GUI or CLI
   */
  'display-name'?: string;
  subnet?: SwitchVlanSubnet;

  /**
   * the VLAN ID
   */
  'vlan-id': number;
}
