// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */

/**
 * Op state attributes
 */
export interface SwitchPortState {

  /**
   * status of the port: up|down
   */
  connected?: string;

  /**
   * the speed reported by the port
   */
  'observed-speed'?: string;
}
