// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SwitchVlan } from './switch-vlan';

/**
 * a list of VLANs (list)
 */
export type SwitchVlanList = Array<SwitchVlan>;
