// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
export type SwitchModelPortSpeeds = Array<'speed-100g' | 'speed-10g' | 'speed-1g' | 'speed-2-5g' | 'speed-25g' | 'speed-400g' | 'speed-40g' | 'speed-5g' | 'speed-autoneg'>;
