// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SwitchPort } from './switch-port';

/**
 * A port in a switch (list)
 */
export type SwitchPortList = Array<SwitchPort>;
