// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { SwitchModelPort } from './switch-model-port';

/**
 * A port in a switch (list)
 */
export type SwitchModelPortList = Array<SwitchModelPort>;
