// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { PathValue } from './path-value';
export interface PathTarget {
  path?: string;
  'path-value'?: PathValue;
}
