// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { Index } from './index';
export interface RollbackTransaction {

  /**
   * the index of the transaction to roll back
   */
  rollback_index?: Index;
}
