// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
export enum State {
  Pending = 'PENDING',
  Validated = 'VALIDATED',
  Applied = 'APPLIED',
  Failed = 'FAILED'
}
