// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { CommitPhaseState } from './commit-phase-state';
import { TransactionPhaseStatus } from './transaction-phase-status';
export interface TransactionCommitPhase {
  state?: CommitPhaseState;
  status?: TransactionPhaseStatus;
}
