// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { AbortPhaseState } from './abort-phase-state';
import { TransactionPhaseStatus } from './transaction-phase-status';
export interface TransactionAbortPhase {
  state?: AbortPhaseState;
  status?: TransactionPhaseStatus;
}
