// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
import { End } from './end';
import { Start } from './start';
export interface TransactionPhaseStatus {
  end?: End;
  start?: Start;
}
