// Code generated by openapi-gen. DO NOT EDIT.
/* tslint:disable */
/* eslint-disable */
export enum ValidatePhaseState {
  Validating = 'VALIDATING',
  Validated = 'VALIDATED',
  Failed = 'FAILED'
}
